##
## 常规的 Prometheus 配置
##
global:
  # 评估间隔
  evaluation_interval: 5s
  # 外部标签
  external_labels:
    source: promxy

# 规则文件指定一组通配符。所有匹配的文件中都会读取规则和警报。
rule_files:
- "*rule"

# Alerting 指定与 Alertmanager 相关的设置。
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "127.0.0.1:12345"

# remote_write 配置用于 promxy 作为其本地 Appender 使用，意味着 promxy 将发送所有“写入”（而不是导出）的指标到这里。
# 这些包括：记录规则、警报规则上的指标等。
remote_write:
  - url: http://localhost:8083/receive

##
### Promxy 配置
##
promxy:
  server_groups:
    # 所有上游 Prometheus 服务发现机制都使用相同的标记，全部在 https://github.com/prometheus/prometheus/blob/master/discovery/config/config.go#L33 中定义
    - static_configs:
        - targets:
          - localhost:9090
      # 要添加到从此 server_group 检索到的指标的标签
      labels:
        sg: localhost_9090
      # 在 server_group 中的主机之间合并时间序列值的反亲和性
      anti_affinity: 10s
      # 等待服务器响应头的时间，单位毫秒
      timeout: 5s
      # 控制是否使用 remote_read 还是 prom API 用于获取远程 RAW 数据（例如矩阵选择器）
      # 注意，某些 Prometheus 实现（例如 VictoriaMetrics）不支持 remote_read。
      remote_read: true
      # 配置发送远程读取请求的路径。默认为 "api/v1/read"
      remote_read_path: api/v1/read
      # path_prefix 定义要添加到此 servergroup 中所有查询的前缀
      # 这可以使用 __path_prefix__ 进行重标记
      path_prefix: /example/prefix
      # query_params 将以下查询参数映射添加到下游请求。
      # 最初的用例是将 `nocache=1` 添加到 VictoriaMetrics 下游
      query_params:
        nocache: 1
      # 配置用于请求的协议方案。默认为 http
      scheme: http
      # promxy 与 server_groups 中的主机通信时的 HTTP 客户端选项
      http_client:
        # 连接下游的等待时间，默认为 200 毫秒。
        dial_timeout: 1s
        tls_config:
          insecure_skip_verify: true

      # relative_time_range 定义相对于当前时间的时间范围，此 server_group 包含该范围内的数据。
      # 这是完全可选的，start/end 也都是可选的
      # 例如，如果此 servergroup 仅包含最近的 3 小时数据
      # "start" 将为 -3h，而 end 将被省略
      relative_time_range:
        start: -3h
        end: -1h
        truncate: false

      # 在合并样本流时，将优先考虑给定时间戳的最大值
      prefer_max: false

      # absolute_time_range 定义此 server_group 包含的绝对时间范围。
      # 这是完全可选的，start/end 也都是可选的
      # 例如，如果 servergroup 已被弃用且不再接收数据
      # 您可以设置其具有数据的特定时间。
      absolute_time_range:
        start: '2009-10-10T23:00:00Z'
        end: '2009-10-11T23:00:00Z'
        truncate: true

    # 可以有任意数量的其他 server_groups
    - static_configs:
        - targets:
          - localhost:9091
      labels:
        sg: localhost_9091
      anti_affinity: 10s
      scheme: http
      http_client:
        tls_config:
          insecure_skip_verify: true
      # ignore_error 将使给定安全组的响应“可选”
      # 这意味着如果此 servergroup 返回错误而其他 servergroup 不返回，则总体查询仍然可以成功
      ignore_error: true
